sudo: required

services:
  - docker

before_install:
  - docker build -t wongni/react-test -f client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wongni/react-test npm test

after_success:
  - docker build -t wongni/multi-client ./client
  - docker build -t wongni/multi-nginx ./nginx
  - docker build -t wongni/multi-server ./server
  - docker build -t wongni/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push wongni/multi-client
  - docker push wongni/multi-nginx
  - docker push wongni/multi-server
  - docker push wongni/multi-worker

#   Set the region. The region code can be found by clicking the region in the toolbar next to your username.
# eg: 'us-east-1'

# app should be set to the EBS Application Name
# eg: 'multi-docker'

# env should be set to your EBS Environment name.
# eg: 'MultiDocker-env'

# Set the bucket_name. This can be found by searching for the S3 Storage service. Click the link for the elasticbeanstalk bucket that matches your region code and copy the name.

# eg: 'elasticbeanstalk-us-east-1-923445599289'

# Set the bucket_path to 'docker-multi'

# Set access_key_id to $AWS_ACCESS_KEY

# Set secret_access_key to $AWS_SECRET_KEY

